server:
  port: 8001
  
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 50
      
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 13065095735
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  activemq:
        broker-url: tcp://localhost:61616
        user: admin
        password: admin
        pool:
         # 使用flase,此处改为true报错，不清楚什么原因
          enabled: false
          max-connections: 10

mybatis:
  mapper-locations: classpath:/com/zFrame/dao/Mapper/*.xml
  type-aliases-package: com.zFrame.entity
  